### PR TITLE
Implement a filter that matches start/end datetime - can be used for future-date scheduling

### PR DESCRIPTION
**Pull request by lyricnz**
Per #228

### CODE REVIEW

**Comment by lyricnz** [comment]
Sample filter:

```yaml
            - name: 'turn it all in in 2021'
              filter:
                - type: ec2
                - accountId: '112233445566'
                - matchWindow:
                    from: '2021-01-01'
                    to: '2022-01-01'
              schedule: '24x7'
              priority: 50
```

**Comment by lyricnz** [comment]
You'll have to be super-careful using these filters - especially around timezones (implicit/local vs explicit), and around 00:00 being the default time of day.

**Comment by lyricnz** [comment]
If a date without a time is specified as from/to value, then it is implicitly 00:00, which makes for somewhat counter-intuitive need to +1 on the end date in order to get 24hour event coverage.

**Review by abukharov — APPROVED** [review]
+1

**Pull request merged**
