### PR TITLE
Add webpack bundling

### PR DESCRIPTION
**Pull request by alutman-innablr**
Addresses https://github.com/Innablr/revolver/issues/87.

* Added in webpack bundling. `npm run bundle` still produces a zip with revolver.js, it's just now a single bundled file and minified.
* Caught top level errors and manually handled the error. Otherwise the bundled js will produce an error on line 2 that prints the entire program.

UPDATED:

Webpack seems to ignore the dynamic loading when using ES2015 imports. This might be a compatibility issue with the typescript compiler module being set to `commonjs` and the ts-loader plugin for webpack. Changing the dynamic `import` to `require` and using "stringish" paths seems to work.

Webpack supports dynamic loading out of the box but it needs to know at least _some_ of the path as a string. `require(varName)` isn't supported, it needs to at least be `require('./plugin/${varName}')`. See https://webpack.js.org/guides/code-splitting/

### CODE REVIEW

**Comment by lyricnz** [comment]
As discussed in slack: webpack isn't including the dynamically-loaded modules (plugins and drivers).

Adding these explicitly to webpack.config.cjs means they are included, but the actual imports fail (cannot find ../plugins/whatever etc). Seems this needs some magic:
- https://webpack.js.org/guides/code-splitting/#dynamic-imports
- https://webpack.js.org/guides/dependency-management/#require-with-expression

But this is beyond my typescript-foo.

**Review by lyricnz — DISMISSED** [review]
https://blog.bitsrc.io/6-tools-and-techniques-to-analyze-webpack-bundle-size-817337f8cf91

image

**Comment by simon-anz** [comment]
Getting some work on my work machine: any ideas?

image

**Review by lyricnz — APPROVED** [review]
LGTM. Tested in client environment Lambda

**Pull request merged**
